---
- name: Stage1 provisioning
  hosts: localhost
  remote_user: root
  become: true

  tasks:
    - name: Stop upgrades
      ansible.builtin.systemd:
        name: "{{ items }}" 
        state: stopped
        enabled: false

      with_items:
        - apt-daily-upgrade.timer
        - apt-daily-upgrade.service
        - unattended-upgrades.service

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Create nginx ssl directory
      ansible.builtin.file:
        name: /etc/nginx/ssl
        state: directory
