---
- name: Stage1 provisioning
  hosts: localhost
  remote_user: root
  become: true

  tasks:

    - name: Stop automatic upgrades
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false

      with_items:
        - apt-daily-upgrade.timer
        - apt-daily-upgrade.service
        - unattended-upgrades.service


    - name: Installing packages
      apt:
        name: 
          - php7.4-fpm
          - php7.4-cli
          - php7.4-mysql
          - php7.4-json
          - php7.4-curl
          - nginx
          - jq
          - environment-modules
          - nfs-common
        state: present

    - name: Create nginx ssl directory
      file:
        name: /etc/nginx/ssl
        state: directory

    - name: Generate SSL certificates
      openssl_certificate:
        path: /etc/nginx/ssl
        privatekey_path: /etc/nginx/ssl/nginx.key
        certificate_path: /etc/nginx/ssl/nginx.crt
        days: 365
        privatekey_size: 2048

    - name: Delete nginx directories
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent

      with_items:
        - /etc/nginx/sites-enabled/default-https
        - /etc/nginx/sites-enabled/default

    - name: Download the nginx default template
      get_url:
        url: https://raw.githubusercontent.com/christophernhill/prov-profiles/main/ronin/ubuntu20/all-in-one/nginx-default.template
        dest: /etc/nginx/sites-available/default-http
          
