---
- name: Stage1 provisioning
  hosts: localhost
  remote_user: root
  become: true

  tasks:

    - name: Stop automatic upgrades
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false

      with_items:
        - apt-daily-upgrade.timer
        - apt-daily-upgrade.service
        - unattended-upgrades.service

    - name: install nginx
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present

      with_items:
        - php7.4-fpm
        - php7.4-cli
        - php7.4-mysql
        - php7.4-json
        - php7.4-curl
        - nginx
        - jq
        - environment-modules
        - nfs-common

    - name: Create nginx ssl directory
      ansible.builtin.file:
        name: /etc/nginx/ssl
        state: directory

    - name: Delete nginx directories
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent

      with_items:
        - /etc/nginx/sites-enabled/default-https
        - /etc/nginx/sites-enabled/default

