---
- name: Stage1 provisioning
  hosts: localhost
  remote_user: root
  become: true

  tasks:
    - name: Stop upgrades
      ansible.builtin.systemd:
        name: apt-daily-upgrade.timer 
        state: stopped
        enabled: false

    - name: Stop upgrade service
      ansible.builtin.systemd:
        name: apt-daily-upgrade.service
        state: stopped
        enabled: false

    - name: Stop unattended upgrades
      ansible.builtin.systemd:
        name: unattended-upgrades.service
        state: stopped
        enabled: false

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Create nginx ssl directory
      ansible.builtin.file:
        name: /etc/nginx/ssl
        state: directory
