---
- name: Stage1 provisioning
  hosts: localhost
  remote_user: root
  become: true

  tasks:
    - name: Installing packages
      apt:
        name:
          - php7.4-fpm
          - php7.4-cli
          - php7.4-mysql
          - php7.4-json
          - php7.4-curl
          - nginx
          - jq
          - environment-modules
          - nfs-common
          - fail2ban

        state: present

    - name: Create nginx ssl directory
      file:
        name: /etc/nginx/ssl
        state: directory

    - name: Delete nginx directories
      ansible.builtin.file:
        name: 
          - /etc/nginx/sites-enabled/default-https
          - /etc/nginx/sites-enabled/default
        state: absent

    - name: Download the nginx default template
      get_url:
        url: https://raw.githubusercontent.com/christophernhill/prov-profiles/main/ronin/ubuntu20/all-in-one/nginx-default.template
        dest: /etc/nginx/sites-enabled/default

          #- name: Start nginx
          #  service:
          #    name: nginx
          #    state: started
